// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX--8ScJl6oqShOhXW23A3U9xMgVUOoPw',
    appId: '1:45968954745:web:1b6f9341fbbfe277230ba8',
    messagingSenderId: '45968954745',
    projectId: 'musclii',
    authDomain: 'musclii.firebaseapp.com',
    storageBucket: 'musclii.firebasestorage.app',
    measurementId: 'G-C30FKJ1LC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDadoLPmcD1BLbZ4YV48CnvBYegUd9hl70',
    appId: '1:45968954745:android:950c2e3cafda93c6230ba8',
    messagingSenderId: '45968954745',
    projectId: 'musclii',
    storageBucket: 'musclii.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeYlXOqiHWNKWfmAw4bagX2FaldrYi0L4',
    appId: '1:45968954745:ios:473ca63737cb2329230ba8',
    messagingSenderId: '45968954745',
    projectId: 'musclii',
    storageBucket: 'musclii.firebasestorage.app',
    iosClientId: '45968954745-ka6en6evus9akf3ofpr9hgmlrsij62js.apps.googleusercontent.com',
    iosBundleId: 'com.example.musclii2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeYlXOqiHWNKWfmAw4bagX2FaldrYi0L4',
    appId: '1:45968954745:ios:473ca63737cb2329230ba8',
    messagingSenderId: '45968954745',
    projectId: 'musclii',
    storageBucket: 'musclii.firebasestorage.app',
    iosClientId: '45968954745-ka6en6evus9akf3ofpr9hgmlrsij62js.apps.googleusercontent.com',
    iosBundleId: 'com.example.musclii2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX--8ScJl6oqShOhXW23A3U9xMgVUOoPw',
    appId: '1:45968954745:web:1e8b7ea7e247d94e230ba8',
    messagingSenderId: '45968954745',
    projectId: 'musclii',
    authDomain: 'musclii.firebaseapp.com',
    storageBucket: 'musclii.firebasestorage.app',
    measurementId: 'G-EQBNTVYKVW',
  );
}
